# Generated by Django 3.2.20 on 2023-08-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descriptions', models.TextField(max_length=500)),
                ('images', models.ImageField(upload_to='photos/products')),
                ('is_availiable', models.BooleanField(default=True)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('modefied', models.DateTimeField(auto_now=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagories.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
