# Generated by Django 3.2.20 on 2023-08-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_availiable',
            new_name='is_active',
        ),
    ]
