# Generated by Django 3.2.20 on 2023-08-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230829_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
